before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

script: bundle exec rspec

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - rbx-2
  - ruby-head

cache: bundler

bundler_args: --without dev --jobs=3
